(ns blocks.client.templates
  (:require
    blocks.client.templates.raw
    blocks.client.templates.header
    blocks.client.templates.hero
    blocks.client.templates.hero-middle
    blocks.client.templates.letter
    blocks.client.templates.video
    blocks.client.templates.downloads
    blocks.client.templates.braid-conversations
    blocks.client.templates.features-grid
    blocks.client.templates.pricing
    blocks.client.templates.footer
    blocks.client.templates.roadmap
    blocks.client.templates.cta
    blocks.client.templates.feature-highlight
    blocks.client.templates.one-feature
    blocks.client.templates.three-features
    blocks.client.templates.rookie-three-values-text
    blocks.client.templates.pre-footer-menu
    blocks.client.templates.multiple-logo-footer
    blocks.client.templates.quote
    blocks.client.templates.how-it-works))
